In [14]:
import pandas as pd
import librosa

In [4]:
df = pd.read_csv('../data/labels/bnd_voices.csv')
df.head()

              song start  finish   member
0  dear_my_darling   0:08   0:22   Sungho
1  dear_my_darling   0:23   0:36    Riwoo
2  dear_my_darling   0:37   0:51  Jaehyun
3  dear_my_darling   0:52   1:07  Woonhak
4  dear_my_darling   1:08   1:20   Leehan

In [5]:
df.dtypes

song      str
start     str
finish    str
member    str
dtype: object

In [7]:
def convert_to_seconds(time_str):
    parts = time_str.split(":")
    minutes = int(parts[0])
    seconds = int(parts[1])
    total = minutes * 60 + seconds
    return total

convert_to_seconds("1:20")

80

In [13]:
df.columns = df.columns.str.strip()
df.columns
df["start_sec"] = df["start"].apply(convert_to_seconds)
df["finish_sec"] = df["finish"].apply(convert_to_seconds)
df.head()

              song start finish   member  start_sec  finish_sec
0  dear_my_darling  0:08   0:22   Sungho          8          22
1  dear_my_darling  0:23   0:36    Riwoo         23          36
2  dear_my_darling  0:37   0:51  Jaehyun         37          51
3  dear_my_darling  0:52   1:07  Woonhak         52          67
4  dear_my_darling  1:08   1:20   Leehan         68          80

In [17]:
import soundfile as sf

sf.write("../data/processed/test_clip.wav", clip, sr)

In [19]:
for index, row in df.iterrows():
    print(row["song"], row["start_sec"], row["finish_sec"], row["member"])

dear_my_darling 8 22 Sungho
dear_my_darling 23 36 Riwoo
dear_my_darling 37 51 Jaehyun
dear_my_darling 52 67 Woonhak
dear_my_darling 68 80 Leehan
dear_my_darling 81 97 Taesan
123_78_ 14 20 Jaehyun
123_78_ 21 27 Leehan
123_78_ 28 37 Sungho
123_78_ 38 42 Riwoo
123_78_ 43 44 Leehan
123_78_ 45 51 Woonhak
123_78_ 52 58 Taesan
123_78_ 59 70 Riwoo
123_78_ 71 79 Woonhak
123_78_ 80 83 Jaehyun
123_78_ 84 93 Sungho
123_78_ 94 97 Leehan
123_78_ 98 100 Jaehyun
123_78_ 101 107 Riwoo
123_78_ 108 114 Taesan
123_78_ 115 125 Jaehyun
123_78_ 143 149 Leehan
123_78_ 150 155 Sungho
reality 21 184 Taesan
iktoy 13 140 Taesan
smart 8 73 Jaehyun
sway 15 108 Leehan
ttte 8 60 Sungho
winner 0 83 Woonhak
darling 8 74 Riwoo

itterrows used

In [21]:
unique_songs = df["song"].unique()

for song_name in unique_songs:
    y,sr = librosa.load(f"../data/raw_audio/{song_name}.mp3", sr=None)
    song_rows = df[df["song"]==song_name]
    for index, row in song_rows.iterrows():
        start_sample = int(row["start_sec"] * sr)
        end_sample = int(row["finish_sec"] * sr)
        clip = y[start_sample:end_sample]
        sf.write(f"../data/processed/{row['member']}_{index}.wav", clip, sr)